version: 2.18
jobs:
  build: 
    working_directory: ~/development/NodeHW
    docker: 
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm
          command: npm install
      - persist_to_workspace:
          root: ~/development/NodeHW
          paths: .
  publish: 
    working_directory: ~/development/NodeHW
    docker: 
      - image: circleci/node:10.16.3
    steps:
      - attach_workspace:
          at: ~/development/NodeHW
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish
          command: npm publish
workflows:
  version: 2
  build-and-publish:
    jobs:
      - build: 
          filters:
            tags: 
              only: /.*/
            branches:
              only:
                - master
                - publish_public
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
